on: [workflow_dispatch]
name: Deploy DevCenter
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:  
      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # set Azure Subscription
    - name: Set DevCenter Subscription
      uses: azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
          az account set --subscription ${{ secrets.DEVCENTER_SUBSCRIPTION }}

    # Deploy DevCenter to Subscription
    - name: Deploy DevCenter
      uses: azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
          cd bicep
          az deployment group create --resource-group ${{ secrets.DEVCENTER_RG }} --parameters devCenter.bicepparam